# This is a basic workflow to help you get started with Actions

name: Log out

# Controls when the action will run.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_API_PAT }}

      - name: Get latest github-vscode-theme
        id: versions
        run: |
          echo ::set-output name=upstream::$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/primer/github-vscode-theme/releases/latest -u "brianzelip:${{ secrets.GH_API_PAT }}" | jq -r '.tag_name')
          echo ::set-output name=local::$(cat package.json | jq -r '.config.latestUpstream')

      - name: Compute version from tag
        id: formattedVersions
        run: echo "::set-output name=upstreamTrimmed::${{ format( '${{{ steps.versions.outputs.upstream }}} {0} {1}', 'hello', 'world' ) }}"

      - name: Update themes
        if: steps.versions.outputs.local != steps.versions.outputs.upstream
        run: |
          git clone https://github.com/primer/github-vscode-theme.git
          cd ./github-vscode-theme
          git checkout ${{ steps.versions.outputs.upstream }}
          npm ci
          npm run build
          rm ../dist/*.json
          cp themes/*.json ../dist/
          cd ..
          rm -rf ./github-vscode-theme

      - name: Bump versions
        if: steps.versions.outputs.local != steps.versions.outputs.upstream
        run: |
          npm --no-git-tag-version version ${{steps.versions.outputs.upstream}}
          # Runner uses legacy npm v6, so bump v7 lockfile manually with
          # extra step since it refuses to be overwritten via jq output
          jq '.packages[""].version |= "${{steps.versions.outputs.upstream}}"' package-lock.json > temp.json
          mv temp.json package-lock.json

      - name: Update changelog
        if: steps.versions.outputs.local != steps.versions.outputs.upstream
        run: |
          # figure out how to use sed to update changelog
          sed '0,/##/s//## [${{steps.formattedVersions.outputs.upstreamTrimmed}}] - 2021-08-09\n\n&/' CHANGELOG.md
          sed -n -i "$ a [${{steps.formattedVersions.outputs.upstreamTrimmed}}]: https://github.com/primer/github-vscode-theme/releases/tag/v4.1.2" CHANGELOG.md
          cat CHANGELOG.md

      # Runs a set of commands using the runners shell

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
