# This is a basic workflow to help you get started with Actions

name: Log out

# Controls when the action will run.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Clone latest github-vscode-theme
        run: |
          echo 'latest_tag="$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/primer/github-vscode-theme/releases/latest \
            -u "brianzelip:${{ secrets.GH_API_PAT }}" | jq -r '.tag_name')"' >> $GITHUB_ENV
          git clone https://github.com/primer/github-vscode-theme.git ./temp
          cd ./temp
          ls

      # Runs a set of commands using the runners shell

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
